### ISSUE TITLE
How to add categories / custom fields?

### ISSUE THREAD

**Issue by skotzko** [lyoshenka/begemot#8]
Love what you set up—thank you for creating this as a service! 

Saw the instructions about specifying tag in the subject line. 

Is there a way currently supported to add other custom frontmatter e.g. categories?

**Comment by lyoshenka** [comment]
Thanks for the kind words :heart: 

Yep, you can send the full frontmatter at the top of the email (just like a normal Jekyll post), and that will be used instead. If you do that, tags and other things in the subject will be ignored. Give it a try, you'll see how it works.
